Домашнее задание 6 часть 1. Не понял как сделать одновременную замену…
IlyaOrlov/PythonCourseKupno pull request #12
Opened 2021-09-03 07:29 UTC by GeP-Nuie

… в одном файле и почему=то print не всегда корректно срабатывает

2021-09-03 07:44 UTC, GeP-Nuie commented
Возможно сделать одновременную замену в одном файле с помощью словаря?

2021-09-03 12:26 UTC, IlyaOrlov requested changes

2021-09-03 12:26 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_1.py
> +with open('text.txt', 'w') as f:
С точки зрения реализации самого преобразования и работы с файлами - все ОК.
Но очевидно, что код в строках 4-8 и 10-14 практически одинаковый. Лучше создать функцию, которая принимает три аргумента: имя_исходного_файла, имя_выходного_файла и флажок (если True - то, например, меняем пробелы на табуляцию, иначе - табуляцию на пробелы).
И еще... для удобочитаемости (хоть это и весьма субъективная оценка) открытие нескольких файлов стоит разнести по разным строкам. Например, так:
```python
with open('text_tab.txt', 'r') as f_tab, \
        open('text_space.txt', 'w') as f_space:
```

2021-09-03 12:26 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_2.py
> +print(f'I have {dict[1]} and {dict[2]}')
Не хватает исходной строки в явном виде, в которой надо что-то заменять. Например: "I have 1 and 2". И код должен пройти по этой строке (или по словарю) подставляя вместо 1 и 2 соответствующие значения. Если исходный текст будет находиться в файле - алгоритм замены будет практически такой же, что и в задании про табуляцию и пробелы.

2021-09-03 12:26 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_3.py
> +lst = [[random.randrange(1, 10) for _ in range(column)] for _ in range(row)]
random - это хорошо, но какие-то заготовленные неслучайные примеры, тоже стоит проверять.

2021-09-03 12:26 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_3.py
> +del_column(lst)
Функция должна удалять столбцы с указанным числом в указанной матрице. Лучше **x** определять вне функции и передавать его в качестве параметра. Тогда сама функция будет более независимой и сможет работать, например, с данными из файла, не запрашивая лишний раз информацию у пользователя.

2021-09-03 12:26 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_3.py
> +import random
Не сработает, например, для такого примера с x = 2 (т.к. после удаления очередного столбца column уже не соответствует реальному количеству столбцов):
```
lst = [
    [1, 1, 2],
    [1, 2, 1],
    [1, 1, 1]
]
```

2021-09-03 12:26 UTC, IlyaOrlov requested changes
> … в одном файле и почему=то print не всегда корректно срабатывает

Как я понимаю, проблема уже не актуальна.

> Возможно сделать одновременную замену в одном файле с помощью словаря?

Да, если мы откроем файл в соответствующем режиме, например "r+". Но нужно понимать, что указатель текущей позиции в файле (откуда читать, или куда писать) будет все равно один. Поэтому, если мы прочитаем какой-то шаблон и захотим его поменять, нам надо будет вернуться на позицию, где этот шаблон начался. Также, если новая строка окажется длиннее старой, замена может перетереть что-то лишнее. Не говоря уже об аварийных ситуациях, когда по каким-то причинам (в т.ч. внешним) наш скрипт не успеет переписать старый файл, и работа оборвется на половине дела. В этом случае мы вообще можем потерять нормальный исходный файл.
Поэтому общий подход, если мы хотим поменять содержимое того же файла, такой: создаем новый временный файл, куда пишем измененные строки, сохраняем его (закрываем), удаляем исходный файл (функция os.remove(имя_файла) из модуля os) и переименовываем временный файл (os.rename(имя_временного_файла, имя_старого_файла)).

2021-09-07 20:53 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_3.py
> +del_column(lst)
Еще бы **x**  в del_column передать в качестве параметра. Тогда статичную матрицу не придется комментировать. Можно будет просто вызвать del_column с различными матрицами и искомыми числами, в т.ч. и с определенными рандомно.

2021-09-07 20:59 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_1.py
> +with open('text.txt', 'w') as f:
Стало лучше. Но сейчас флажок проверяется дважды: в цикле и в функции. Тогда лучше указать функции что на что менять: tab_space(before, after) и вызывать ее для "tab": tab_space('\t', '    '), а для "space": tab_space('    ', '\t'). Тогда тело функции можно будет легко уменьшить)

2021-09-08 10:54 UTC, IlyaOrlov requested changes

2021-09-08 10:54 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_6_1.py
> +x = input('Если хотите поменять пробелы на табуляцию, то введите tab, если же наоборот, то введите space: ')
Если **x** задается вне цикла, то в случае некорректного ввода у пользователя не будет шанса ввести другой **x**.

2021-09-08 11:30 UTC, IlyaOrlov approved these changes

2021-09-08 11:30 UTC, merged