Домашнее задание 7 часть 2
IlyaOrlov/PythonCourseKupno pull request #14
Opened 2021-09-08 13:07 UTC by GeP-Nuie

Не получается сделать except, т.к. создаю файл вне класса, как правильно прописать tempfile? в init? и делитер как-то странно работает

2021-09-08 18:31 UTC, IlyaOrlov requested changes

2021-09-08 18:31 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_7_2.py
> +fd, path = tempfile.mkstemp(suffix='.txt', dir='E:\Study\PythonCourseKupno\Practice\spodkovyrin', text=True)
При создании файла с использованием mkstemp файл не только создается, но и открывается (система назначает ему дескриптор и считает его открытым). Поэтому если мы попробуем удалить этот файл в делитере (не закрыв fd), то будет ошибка вида "Нельзя удалить файл, т.к. он открыт в другом приложении".
Так что с файлом, созданным с помощью mstemp, нужно либо работать через дескриптор fd, либо закрыть файл и потом открывать по мере необходимости. Можно, например, так (в __init__):
fd, self.path = tf.mkstemp('.txt', 'first', 'test')
os.close(fd)
Альтернативой mkstemp является функция mktemp. Python, правда, будет ругаться, что это небезопасная функция (т.к. она просто генерирует уникальное имя, не создавая файл, и в любой момент это имя может оказаться неуникальным), но для нашей учебной программы особого риска нет)

2021-09-09 05:51 UTC, GeP-Nuie commented
Вы проверили домашнее задание 7 часть 1? а то по нему ничего не написали но закинули в main, или там все правильно?

2021-09-09 09:06 UTC, IlyaOrlov requested changes

2021-09-09 09:06 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_7_2.py
> +            return "File doesn't exist"
Если здесь написать r = "File doesn't exist", то можно обойтись одним return на функцию. Чем меньше точек выхода из функции, тем проще ее контролировать.

2021-09-09 09:06 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_7_2.py
> +path = tempfile.mktemp(suffix='.txt', dir='E:\Study\PythonCourseKupno\Practice\spodkovyrin')
Все-таки я внес бы это в конструктор. Можно передавать в \_\_init\_\_ путь к папке для временных файлов (со значением по умолчанию '' - т.е. текущая папка), но все, что касается самого временного файла - это личное дело экземпляра класса WrapStrToFile.

2021-09-09 11:00 UTC, GeP-Nuie commented
Но так он создает файл не в текущей папке, а создает в юзерах временную папку и уже там файл

2021-09-09 13:56 UTC, IlyaOrlov commented
> Но так он создает файл не в текущей папке, а создает в юзерах временную папку и уже там файл

Тогда можно прописать атрибут dir='.\'  Тогда это точно будет текущая папка.

2021-09-09 18:58 UTC, IlyaOrlov approved these changes

2021-09-09 18:59 UTC, merged