Домашнее задание №8
IlyaOrlov/PythonCourseKupno pull request #15
Opened 2021-09-10 09:54 UTC by GeP-Nuie

2021-09-10 12:43 UTC, IlyaOrlov requested changes

2021-09-10 12:43 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_8_1.py
> +    return [source[i] * m for i, x in enumerate(source)]
Нужно ли нам здесь знать i? Можно просто [x * m for x in source]

2021-09-10 12:43 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_8_2.py
> +    t = time.time()
Лучше сделать это атрибутом экземпляра. И засекать время не посредственно при входе в секцию (\_\_enter\_\_) Иначе могут быть некорректные результаты. Особенно при повторном использовании.

2021-09-10 12:43 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_8_3.py
> +import itertools
Замечание по организации кода: все определения функций стоит перенести наверх, а все вызовы вниз.

2021-09-22 08:41 UTC, GeP-Nuie commented
В 9_2 через type не может найти файл, потому сделал через notepad

2021-09-22 09:15 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_8_2.py
> +    t = time.time()
Уже лучше, но теперь вашим классом ContextManager могут воспользоваться, например, так:
```python
ctx = ContextManager(t = time.time())
# еще какой-то код
with ctx:
    print('Работа с менеджером контекстов')
    input('Отчет по работе: ')
```
В результате мы получим время выполнения всего приведенного кода, начиная с ctx = ContextManager(t = time.time()), а не только блока внутри with, как ожидалось. 
Чтоб время засекалось непосредственно при входе в секцию with, результат time.time() надо запоминать в методе \_\_enter\_\_.

2021-09-22 09:34 UTC, IlyaOrlov requested changes

2021-09-22 09:34 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_1.py
> +work_days(d1, d2, h)
Если указать следующие даты, то в ответе ожидается 5 или 6 (в зависимости от того, включается 17-е сентября или нет):
```python
d1 = date(2021, 9, 17)
d2 = date(2021, 9, 26)
h = []  # или h = ['2021-09-18', '2021-09-19']
work_days(d1, d2, h)
```
Однако, на выходе результат оказывается: 7
К тому же, для решения этой задачи вовсе необязательно привлекать тяжеловесную библиотеку numpy. Можно вполне обойтись datetime, используя обращения к методe d1.weekday() и функции timedelta().

2021-09-22 09:43 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_2.py
> +    proc = run(['notepad.exe', path], stdout=PIPE, stderr=PIPE)
OK. Можно и через "notepad.exe". Это непринципиально.
Т.к. type - это не самостоятельное приложение, а утилита командной строки (shell), то ее следует запускать так: proc = run(['type', path], **shell=True**, stdout=PIPE, stderr=PIPE)

2021-09-22 12:54 UTC, GeP-Nuie commented
В задании 9_3 почему-то десериализация выводит только 1-й экземпляр?

2021-09-22 13:36 UTC, IlyaOrlov requested changes

2021-09-22 13:36 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_3.py
> +import names
Оригинально) Но если бы речь шла о добавлении кода в продакшн, я бы не стал использовать лишний раз стороннюю библиотеку. Во-первых, чтоб не было лишних зависимостей. Во-вторых, чтоб не подтянуть, случаем, какой-нибудь вредоносный код, который может оказаться в этой сторонней библиотеке.

2021-09-22 13:36 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_3.py
> +        dict = ['male', 'female']
Не стоит использовать зарезервированные слова для именования переменных. Тем более dict здесь вроде как список, а не словарь)

2021-09-22 13:36 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_3.py
> +        with open('human.data', 'ab') as f:
Все ОК, только сериализацию объекта также следует вынести в отдельную функцию. Нам вполне может потребоваться возможно генерации людей без сериализации, или сериализация готовых людей. Стоит придерживаться принципа: одна задача - одна функция. Кофемашина с единственной кнопкой для приготовления кофе с молоком - это, конечно, удобно. Но, при этом, мы теряем возможность приготовления только черного кофе, или только горячего молока.

2021-09-22 14:13 UTC, GeP-Nuie commented on Practice/spodkovyrin/home_9_3.py
> +        with open('human.data', 'ab') as f:
Это понятно просто задание звучит так что сериализация должна быть в той же функции что и генератор экземпляров. Но всетаки в чем проблема? Почему десериализация выдает только 1-й экземпляр?

2021-09-22 19:03 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_3.py
> +        with open('human.data', 'ab') as f:
Потому что у вас генерируется только один экземпляр. На первой же итерации цикла for выполняется return и, соответственно, выход из функции generate_human.

2021-09-23 07:31 UTC, GeP-Nuie commented on Practice/spodkovyrin/home_9_3.py
> +        with open('human.data', 'ab') as f:
тогда я что-то не понял как мне вернуть весь список экземпляров?

2021-09-23 08:03 UTC, GeP-Nuie commented
Сделал, меня просто Pycharm смутил, говоря что переменная human в функции нигде не используется, а это не критическая ошибка оказывается, а просто замечание

2021-09-23 09:58 UTC, GeP-Nuie commented
В задании 9_4 столкнулся с проблемой, что при запуске кода вылетает ошибка, что отказано в доступе, но при этом, если есть файлы которые нужно удалить по времени, то скрипт их удаляет, но после этого все равно пишет туже ошибку

2021-09-23 10:12 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_3.py
> +        with open('human.data', 'ab') as f:
Чтоб вернуть список экземпляров - надо создать СПИСОК экземпляров. Что у вас в итоге и получилось. Только вовсе необязательно было делать этот список атрибутом класса. Это вполне мог быть локальный список generate_human. Мы бы его возвращали через return human и передавали в ser.
Класс, хранящий информацию обо всех своих экземплярах - тоже нормальное решение, хотя и несколько непрозрачное и неочевидное.

2021-09-23 10:25 UTC, IlyaOrlov requested changes

2021-09-23 10:25 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_4.py
> +seconds_folders = time.time() - (time_folders * 60)
Расчет seconds_folders и seconds_files стоит внести в цикл, Т.к. пока скрипт работает, может прийти время и других файлов и папок (time.time() же меняется).

2021-09-23 10:25 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_4.py
> +            if seconds_files >= get_age(path):
path - это же путь к папке

2021-09-23 10:25 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_4.py
> +    if not shutil.rmtree(path):
Мы так можем удалить папку, содержащую файлы время которых еще не пришло. В идеале следовало бы запустить в папке рекурсивную проверку (как в строках 37-49).

2021-09-23 10:26 UTC, IlyaOrlov commented
> В задании 9_4 столкнулся с проблемой, что при запуске кода вылетает ошибка, что отказано в доступе, но при этом, если есть файлы которые нужно удалить по времени, то скрипт их удаляет, но после этого все равно пишет туже ошибку

Есть вероятность, что такой файл открыт какой-то программой.

2021-09-23 10:59 UTC, GeP-Nuie commented on Practice/spodkovyrin/home_9_4.py
> +            if seconds_files >= get_age(path):
Это условие, что если заданный path не папка, то мы считаем что это файл и тутже его удаляем

2021-09-23 12:00 UTC, GeP-Nuie commented on Practice/spodkovyrin/home_9_4.py
> +    if not shutil.rmtree(path):
чет не получается сделать рекурсию работающую=) не подскажите как ее тут ввинтить? и отказ в доступе все еще не понятен, нигде этот файл не запущен, если только сам Pycharm к нему как-то обращается?

2021-09-23 16:19 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_4.py
> +            if seconds_files >= get_age(path):
ОК

2021-09-23 16:38 UTC, IlyaOrlov commented on Practice/spodkovyrin/home_9_4.py
> +    if not shutil.rmtree(path):
Поскольку os.walk сама по себе рекурсивно обходит все дерево каталогов и возвращает имена файлов и папок, то, вероятно, возникает ситуация, что где-то мы пытаемся удалить файл или папку повторно. Хорошо бы добавить после 45-й строки print(root_folder, folders, files), чтоб посмотреть, что мы там обходим и удаляем.
В принципе, с os.walk рекурсию самому писать уже не нужно. А вот с os.listdir это бы выглядело примерно так:
```python
def del_in_dir(path_to_dir):
    while True:
        for i in os.listdir(path_to_dir):
            path_of_item = os.path.join(path_to_dir, i) 
            if os.path.isfile(path_of_item):
                # проверяем время файла и, при необходимости, удаляем
            else:
                # для папки сначала запускаем рекурсивную проверку
                del_in_dir(path_of_item)
                # проверяем время папки и, при необходимости, удаляем
```

2021-09-24 10:19 UTC, IlyaOrlov approved these changes

2021-09-24 10:19 UTC, merged