Ntoptygin
IlyaOrlov/PythonCourseKupno pull request #5
Opened 2021-08-12 16:12 UTC by topnikita

2021-08-12 20:03 UTC, IlyaOrlov requested changes

2021-08-12 20:03 UTC, IlyaOrlov commented on Practice/ntoptygin/pep8task.py
> +import os
Файл вижу. Жду комментариев к найденным в файле ошибкам.

2021-08-14 18:15 UTC, IlyaOrlov requested changes

2021-08-14 18:15 UTC, IlyaOrlov commented on Practice/ntoptygin/dz2.py
> +    if a < b:
Это уже проверять не нужно. Раз мы дошли до этой строки, то **а** точно не больше **b**. Т.е. в этом случае можно сразу сделать return b.

2021-08-14 18:15 UTC, IlyaOrlov commented on Practice/ntoptygin/dz1.py
> +x = int(input("Введите первое число для сравнения: "))
С точки зрения стиля надо добавить пустых строк между определением функции и кодом вне функций.

2021-08-14 18:15 UTC, IlyaOrlov commented on Practice/ntoptygin/dz2.py
> +x = int(input("Введите первое число для сравнения: "))
То же замечание: надо добавить пустых строк между определением функции и кодом вне функций.

2021-08-14 18:15 UTC, IlyaOrlov commented on Practice/ntoptygin/pep8task.py
> +from tkinter import Tk, Canvas, PhotoImage, mainloop
В этом файле ожидалось другое задание)

2021-08-14 18:38 UTC, IlyaOrlov approved these changes

2021-08-14 18:38 UTC, merged

2021-08-14 19:00 UTC, IlyaOrlov commented on Practice/ntoptygin/dz2.py
> +    if a < b:
Проверочный комментарий.

2021-08-14 21:00 UTC, topnikita commented on Practice/ntoptygin/dz2.py
> +    if a < b:
Точно, не подумал об этом. Но тогда возникает вопрос. Я попробовал два варианта, код работает одинаково в обоих случаях:
1) def compare(a,b):
    if a > b:
        return a
    return b
2) def compare(a,b):
    if a > b:
        return a
    else:
        return b

То есть получается, что Else писать необязательно?

2021-08-14 21:00 UTC, topnikita commented on Practice/ntoptygin/pep8task.py
> +from tkinter import Tk, Canvas, PhotoImage, mainloop
Упс))

2021-08-14 21:36 UTC, IlyaOrlov commented on Practice/ntoptygin/dz2.py
> +    if a < b:
Ага, теперь комментарий виден. 
Продублирую ответ: в данном случае else действительно не нужен, т.к. первый return (если его условие истинно) сразу же приведет к выходу из функции