pull request
IlyaOrlov/PythonCourseKupno pull request #7
Opened 2021-08-29 15:13 UTC by topnikita

Сделал домашнее задание номер 3

2021-08-30 10:40 UTC, IlyaOrlov requested changes

2021-08-30 10:40 UTC, IlyaOrlov commented on Practice/ntoptygin/dz5.py
> +    if a.lower()[::-1] == a.lower():
Стоит использовать вспомогательную переменную (либо ту же **a**), чтоб не вызывать метод lower() дважды для одной и той же строки.

2021-08-30 10:40 UTC, IlyaOrlov commented on Practice/ntoptygin/dz6.py
> +c = '1'
А что если это исходное значение совпадет с загаданным?

2021-08-30 20:18 UTC, topnikita commented on Practice/ntoptygin/dz6.py
> +c = '1'
Хороооший вопрос

2021-08-31 08:44 UTC, IlyaOrlov commented on Practice/ntoptygin/dz6.py
> +c = number + 1
Оригинально:) Я бы, пожалуй, для инициализации использовал None (это универсальный подход, для таких случаев, собственно, None и нужен), а **с** к int приводил не в 14-й строке, а где-нибудь после 18-й:
```python
c = None
while c != number:
    c = input('Окей, теперь давайте угадывать. Введите число. ')
    if not c.isnumeric():
        print('К сожалению, Вы ввели не числовое значение, приходите завтра.')
        break
    c = int(c)
    if c < number:
        print('Введенное число меньше загаданного')
    elif c > number:
        print('Введенное число больше загаданного')
    else:
        print('Ура, Вы угадали!')
```
Но в рамках данной задачи так тоже можно)

2021-08-31 08:44 UTC, IlyaOrlov approved these changes

2021-08-31 08:44 UTC, merged